apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: sriharipriya/hello-world:${{ github.run_number }}

          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-loadbalancer-service
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - port: 8080
      targetPort: 8080
